### ISSUE TITLE
MobXCaughtException

### ISSUE THREAD

**Issue by danfq** [firmino2611/group_select#1]
Upon opening a page with the Widget, the respective Controller returns - ```MobXCaughtException: Bad state: No element```.

This happens every time the page is loaded - regardless of the Widget Hierarchy.

**Comment by firmino2611** [comment]
First thanks for the feedback. I will check the bug, if possible could you post the snippet of your code here.

**Comment by firmino2611** [comment]
I could not reproduce the error. If possible send me a screenshot of the console to better understand the problem.
